# Generated by Django 4.2.2 on 2023-07-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientinrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='unique_ingredient_in_recipe',
        ),
    ]
