# Generated by Django 4.2.2 on 2023-07-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientinrecipe_unique_ingredient_in_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favourites',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='unique_ingredient_in_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart',
        ),
    ]
